apiVersion: v1
kind: Service
metadata:
  name: glimpse-service-message
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: glimpse-service-message
  type: LoadBalancer