apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glimpse-service-message
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glimpse-service-message
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-p", "8081",
          "-a", "127.0.0.1:5000",
          "-s", "glimpse-service-message.endpoints.glimpse-123456.cloud.goog",
          "-v", "2017-08-12r0",
        ]
        ports:
          - containerPort: 8081
      - name: message
        image: gcr.io/glimpse-123456/glimpse-service-message:latest
        ports:
          - containerPort: 5000
        env:
        - name: CASSANDRA_HOST
          value: cassandra
        - name: GLIMPSE_SERVICE_ASSET
          value: asset
